apiVersion: v1
kind: Pod
metadata:
  generateName: audit-pod-
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/2aff5d4800d3c60f930b6f10188bc2ca4d366359246bec86de6dc0d6ed61d818.json
  restartPolicy: Never
  containers:
  - name: test-container
    image: cgr.dev/chainguard/busybox
    command: ['sh', '-c', 'echo making some syscalls']
    securityContext:
      allowPrivilegeEscalation: false
