# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.seccomp.imjasonh.dev
  labels:
    seccomp.imjasonh.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: seccomp-profile
  failurePolicy: Fail
  sideEffects: None
  name: defaulting.seccomp.imjasonh.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.seccomp.imjasonh.dev
  labels:
    seccomp.imjasonh.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: seccomp-profile
  failurePolicy: Fail
  sideEffects: None
  name: validation.seccomp.imjasonh.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.seccomp.imjasonh.dev
  labels:
    serving.knative.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: seccomp-profile
  failurePolicy: Fail
  sideEffects: None
  name: config.seccomp.imjasonh.dev
  namespaceSelector:
    matchExpressions:
    - key: seccomp.imjasonh.dev/release
      operator: Exists
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating.seccomp.imjasonh.dev
webhooks:
- name: mutating.seccomp.imjasonh.dev
  namespaceSelector:
    # The webhook should only apply to things that opt-in
    matchExpressions:
    - key: seccomp.imjasonh.dev/include
      operator: In
      values: ["true"]
  admissionReviewVersions: [v1]
  clientConfig:
    service:
      name: webhook
      namespace: seccomp-profile
  failurePolicy: Fail
  sideEffects: NoneOnDryRun
  timeoutSeconds: 25
  reinvocationPolicy: IfNeeded
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: seccomp-profile
  labels:
    seccomp.imjasonh.dev/release: devel
# The data is populated at install time.
