# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller
  namespace: seccomp-profile
  labels:
    seccomp.imjasonh.dev/release: devel
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
        seccomp.imjasonh.dev/release: devel
    spec:
      serviceAccountName: controller
      volumes:
      - name: profiles
        hostPath:
          path: /var/lib/kubelet/seccomp/profiles  # If the kubelet path is different, change it here.
          type: Directory
      containers:
      - name: controller
        image: ko://github.com/imjasonh/seccomp-profile/cmd/controller
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        volumeMounts:
        - name: profiles
          mountPath: /profiles
        ports:
        - name: metrics
          containerPort: 9090
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: imjasonh.dev/seccomp
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0  # TODO: Don't run as root.
